### ISSUE TITLE
Project TODO list

### ISSUE THREAD

**Issue by provigz** [Vankata453/addons-website-prototype#1]
This list is a collection of planned features for the website. It may be edited at any time to accompany new ideas, or mark progress. If you wish to help with any of these, feel free to do so!

- [ ]  **Welcome page**: Currently does not exist. It is planned to include a welcome text, short description of the site's purpose and show short most downloaded/most reviewed add-on lists. A random add-on being shown would also be a nice addition.
- [ ] **Add-on licensing options**: Currently, they do not exist, and temporary placeholders take their place.
- [ ] **Add-on verification**: Users could be given moderator or admin permissions, by current admins on the website, either of which will allow verifying add-ons. Other moderation options for users with these privileges would be added as well.
- [x] **Reviews**: Currently not supported. Users should be able to review add-ons, but have the first review from their account be required a review. Reviews should be shown on add-on pages, an example position being under the general add-on info. Above all reviews an add-on has, a text field for filling out a review should be available, as well as an applet, which helps the user give a rating via their review. A user should only be able to review an add-on once.
- [ ] **Download counts for add-ons**: Planned.
- [ ] **More in-depth styling of the front-end part of the website**: Could take place in the future.
